1. Create a 5X2 integer array from a range between 100 to
200 such that the difference between each element is 10

In [1]:
import numpy as np
arr = np.arange(100, 200, 10)
arr = arr.reshape(5,2)
print (arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Write a NumPy program to create a 3x3x3 array filled
with arbitrary values and find the minimum and maximum
values.

In [2]:
import numpy as np
x = np.random.random((3, 3, 3))
print(x)

print("\nThe maximum value is :",x.max())
print("\nThe minimum value is :",x.min())

[[[0.56095529 0.67080795 0.15110432]
  [0.55576504 0.54198494 0.28443202]
  [0.65306956 0.39307886 0.46202142]]

 [[0.71588975 0.9289251  0.43808148]
  [0.20367298 0.11019106 0.74205637]
  [0.13484368 0.50006497 0.39416855]]

 [[0.30639356 0.50702077 0.11273358]
  [0.20527579 0.82765813 0.7689282 ]
  [0.07178407 0.35351955 0.89429364]]]

The maximum value is : 0.9289250960554367

The minimum value is : 0.07178407240091511


3. Write a NumPy program to create a 5x5 zero matrix
with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [3]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


4. Given an array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
i) Extract all odd numbers from arr
ii) Replace all odd numbers in arr with -1

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("odd number ", arr[arr%2!=0])

ar=[x if x%2==0 else -1 for x in arr]
print(ar)



odd number  [1 3 5 7 9]
[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


5.Write a NumPy program to create a 3x3 identity matrix,
i.e. diagonal elements are 1,the rest are 0.

In [5]:
import numpy as np
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

6. Write a NumPy program to convert an array to a float
type.

In [6]:
import numpy as np
a = [3, 4, 7, 8]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted into float type:")
print(x)

Original array
[3, 4, 7, 8]
Array converted into float type:
[3. 4. 7. 8.]


7. Write a NumPy program to generate five random
numbers from the normal distribution.

In [7]:
import numpy as np
x = np.random.normal(size=5)
print(x) 

[-0.05551648 -0.01642459  0.66022735  0.89901749  0.37268829]


8. Following is the input NumPy array delete column two
and insert following new column in its place.

sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,
66]])
newColumn = numpy.array([[10,10,10]])

In [8]:
import numpy as np

print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


9. Write a NumPy program to compute the multiplication
of two given matrices.

In [9]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[3,4],[5,6]])
A.dot(B)


array([[13, 16],
       [29, 36]])

10. Write a NumPy program to create a random vector of
size 10 and sort it.

In [10]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.26809842 0.3211669  0.68908018 0.05251467 0.55576398 0.70902547
 0.56285956 0.65272943 0.82470665 0.92789867]
Sorted array:
[0.05251467 0.26809842 0.3211669  0.55576398 0.56285956 0.65272943
 0.68908018 0.70902547 0.82470665 0.92789867]


11. Write a NumPy program to compute the covariance
matrix of two arrays.

In [11]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array2:")
print(y)
print("\nCovariance matrix of the arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array2:
[2 1 0]

Covariance matrix of the arrays:
 [[ 1. -1.]
 [-1.  1.]]


12.Create a 4X2 integer array and Prints its :
i)The shape of an array.
ii) Array dimensions.
iii) The Length of each element of the array in bytes

In [12]:
import numpy as np

firstArray = np.empty([4,2], dtype = np.uint16) 

print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)


Printing Array
[[    0     0]
 [    0 16368]
 [    0     0]
 [    0 16368]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


13. Write a NumPy program to concatenate element-wise
two arrays of string.

In [13]:
import numpy as np
x1 = np.array(['Jay','Swarna'], dtype=np.str)
x2 = np.array(['Analyst','Programmer'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

Array1:
['Jay' 'Swarna']
Array2:
['Analyst' 'Programmer']
new array:
['JayAnalyst' 'SwarnaProgrammer']


14. Write a NumPy program to capitalize the first letter,
lowercase, uppercase, swapcase, title-case of all the
elements of a given array.

In [14]:
import numpy as np
x = np.array(['Python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['Python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['pYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


15. Write a NumPy program to convert a given array into
a list.

In [15]:
import numpy as np

arr = np.array([1, 2, 3])

print(f'NumPy Array:\n{arr}') 

list1 = arr.tolist()

print(f'List: {list1}')

NumPy Array:
[1 2 3]
List: [1, 2, 3]


16. Write a NumPy program to compute the sum of all
elements, sum of each column and sum of each row of a
given array.

In [16]:
import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


17. Write a NumPy program to create a random 10x4
array and extract the first five rows of the array and store
them into a variable.

In [17]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.85334044 0.71645414 0.04732911 0.46803161]
 [0.51981205 0.86070397 0.06180347 0.74666261]
 [0.96076425 0.1758663  0.49072376 0.42634756]
 [0.75547829 0.81050268 0.7246538  0.77404923]
 [0.658864   0.32936132 0.94023261 0.40459018]
 [0.78081998 0.82794424 0.62288927 0.11033111]
 [0.27181779 0.70106398 0.75178332 0.584043  ]
 [0.70585621 0.13450357 0.62491578 0.77667091]
 [0.02451545 0.22788395 0.90814274 0.70883463]
 [0.67046961 0.41020795 0.20069409 0.3942618 ]]
First 5 rows of the above array:
[[0.85334044 0.71645414 0.04732911 0.46803161]
 [0.51981205 0.86070397 0.06180347 0.74666261]
 [0.96076425 0.1758663  0.49072376 0.42634756]
 [0.75547829 0.81050268 0.7246538  0.77404923]
 [0.658864   0.32936132 0.94023261 0.40459018]]


18. Write a NumPy program to get the unique elements of
a 1D and 2D array.

In [18]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original 1 D array:")
print(x)
print("Unique elements of 1 D array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original 2 D array:")
print(x)
print("Unique elements of 2 D array:")
print(np.unique(x))

Original 1 D array:
[10 10 20 20 30 30]
Unique elements of 1 D array:
[10 20 30]
Original 2 D array:
[[1 1]
 [2 3]]
Unique elements of 2 D array:
[1 2 3]


19. Write a NumPy program to get the unique elements of
an array.
arr= [ -10,12,12,-2]

In [19]:
import numpy as np
x=np.array([-10,12,12,-2])
print("Original array: ")
print(x)
print("Unique elements in an array: ")
print(np.unique(x))


Original array: 
[-10  12  12  -2]
Unique elements in an array: 
[-10  -2  12]


20. Write a NumPy program to save a given array to a text
file and load it. You have to save and load file using
numpy library .

In [20]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
